### PR TITLE
Update toolchanger.cfg

### PR DESCRIPTION
**Pull request by BrewNinja**
Changed homing_rebound_y description to be valid

### CODE REVIEW

**Comment by TheSin-** [comment]
You changed the desk for safe_y rebound didn’t have a desc

**Comment by BrewNinja** [comment]
Oh boy. I always read the descriptions as above what you are going to change next. WIll fix it.

**Comment by TheSin-** [comment]
You can move to that format if you want move em all I’m okay which eitherway hoenstly

**Comment by BrewNinja** [comment]
I updated it to be similar to most other comments in files with it right after the option. Leaves less ambiguity. Also, Im an idiot and was looking at totally wrong things before.

**Comment by TheSin-** [comment]
Perfect thank you

**Pull request merged**
